version: '3.8'
services:
  web:
    build: .
    image: hussain2012/app:v1
    ports:
      - '80:8080'
    environment:
      DATABASE_URL: postgres://pokeuser:pokepass@db:5432/pokedex
    networks:
      pgnodeapp:
    depends_on:
      - "db"
    container_name: web
    command: ["./wait-for", "postgres:5432", "-t", "60", "--", "npm", "run", "db:migrate-seed"]

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: pokeuser
      POSTGRES_PASSWORD: pokepass
      POSTGRES_DB: pokedex
    container_name: db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      pgnodeapp:
        aliases:
          - 'postgres'

networks:
  pgnodeapp:
    driver: bridge

volumes:
  postgres-db:
